import { describe, expect, it } from 'vitest';
import { chachaBlock, chachaBlockWords, chacha20Xor } from './chacha20';
import { Rng, popcount32 } from './rng';

/**
 * SPEC KATs — RFC 8439, "ChaCha20 and Poly1305 for IETF Protocols".
 *
 * These are the only published test vectors any primitive in this lab has, and
 * they anchor the sampler every ciphertext on the page is drawn from. They are
 * quoted from the RFC, not generated by this implementation, which is the whole
 * distinction between a known-answer test and a regression snapshot.
 */

function hex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

function fromHex(s: string): Uint8Array {
  const clean = s.replace(/[^0-9a-f]/gi, '');
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i += 1) out[i] = parseInt(clean.substr(i * 2, 2), 16);
  return out;
}

describe('ChaCha20 — RFC 8439 known-answer tests', () => {
  // RFC 8439 §2.3.2: the block function test vector.
  const KEY_2_3_2 = fromHex('000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f');
  const NONCE_2_3_2 = fromHex('000000090000004a00000000');

  it('§2.3.2 — block function, counter 1', () => {
    const block = chachaBlock(KEY_2_3_2, 1, NONCE_2_3_2);
    // Laid out sixteen bytes to a line, exactly as the RFC prints it.
    expect(hex(block)).toBe(
      '10f1e7e4d13b5915500fdd1fa32071c4' +
        'c7d1f4c733c068030422aa9ac3d46c4e' +
        'd2826446079faa0914c2d705d98b02a2' +
        'b5129cd1de164eb9cbd083e8a2503c4e'
    );
  });

  it('§2.3.2 — the initial state is the constants, key, counter, nonce', () => {
    // The first four output words are the working state plus the sigma
    // constants; checking the words form rather than only the bytes catches a
    // little-endian slip in serialization that the byte vector alone would
    // attribute to the round function.
    const words = chachaBlockWords(KEY_2_3_2, 1, NONCE_2_3_2);
    expect(words.length).toBe(16);
    expect(words[0] >>> 0).toBe(0xe4e7f110);
  });

  it('§2.4.2 — encrypting the sunscreen plaintext, counter 1', () => {
    const key = fromHex('000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f');
    const nonce = fromHex('000000000000004a00000000');
    const plaintext = new TextEncoder().encode(
      "Ladies and Gentlemen of the class of '99: If I could offer you only one tip for " +
        'the future, sunscreen would be it.'
    );
    const ciphertext = chacha20Xor(key, 1, nonce, plaintext);
    expect(hex(ciphertext)).toBe(
      '6e2e359a2568f98041ba0728dd0d6981' +
        'e97e7aec1d4360c20a27afccfd9fae0b' +
        'f91b65c5524733ab8f593dabcd62b357' +
        '1639d624e65152ab8f530c359f0861d8' +
        '07ca0dbf500d6a6156a38e088a22b65e' +
        '52bc514d16ccf806818ce91ab7793736' +
        '5af90bbf74a35be6b40b8eedf2785e42' +
        '874d'
    );
  });

  it('§2.4.2 — decryption is the same operation', () => {
    const key = fromHex('000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f');
    const nonce = fromHex('000000000000004a00000000');
    const message = new TextEncoder().encode('the shelf keeps no record of what you asked for');
    const roundTrip = chacha20Xor(key, 1, nonce, chacha20Xor(key, 1, nonce, message));
    expect(hex(roundTrip)).toBe(hex(message));
  });
});

describe('the sampler built on it', () => {
  it('popcount32 agrees with a naive count over the boundary cases', () => {
    for (const v of [0, 1, 0xffffffff, 0x80000000, 0x0f0f0f0f, 123456789]) {
      let naive = 0;
      for (let i = 0; i < 32; i += 1) if ((v >>> i) & 1) naive += 1;
      expect(popcount32(v)).toBe(naive);
    }
  });

  it('a seeded run is reproducible and a different seed is not', () => {
    const a = Rng.fromSeed('shelf-oracle');
    const b = Rng.fromSeed('shelf-oracle');
    const c = Rng.fromSeed('shelf-oracl3');
    const draw = (r: Rng): number[] => Array.from({ length: 16 }, () => r.uniformBelow(1 << 20));
    const first = draw(a);
    expect(draw(b)).toEqual(first);
    expect(draw(c)).not.toEqual(first);
  });

  it('crosses the 64-byte block boundary without repeating', () => {
    const rng = Rng.fromSeed('block-boundary');
    const bytes = new Uint8Array(200);
    rng.fill(bytes);
    // Blocks 0, 1 and 2 must all differ; a counter that never increments would
    // repeat the first 64 bytes verbatim.
    expect(hex(bytes.subarray(0, 64))).not.toBe(hex(bytes.subarray(64, 128)));
    expect(hex(bytes.subarray(64, 128))).not.toBe(hex(bytes.subarray(128, 192)));
    expect(rng.bytesDrawn).toBe(200);
  });

  it('uniformBelow stays in range and covers it', () => {
    const rng = Rng.fromSeed('range');
    const seen = new Set<number>();
    for (let i = 0; i < 4000; i += 1) {
      const v = rng.uniformBelow(17);
      expect(v).toBeGreaterThanOrEqual(0);
      expect(v).toBeLessThan(17);
      seen.add(v);
    }
    expect(seen.size).toBe(17);
  });

  it('uniformBelow refuses a bound it cannot sample without bias', () => {
    const rng = Rng.fromSeed('bad-bound');
    expect(() => rng.uniformBelow(0)).toThrow(RangeError);
    expect(() => rng.uniformBelow(2 ** 33)).toThrow(RangeError);
  });

  it('ternary is supported on exactly {-1, 0, 1}', () => {
    const rng = Rng.fromSeed('ternary');
    const counts = new Map<number, number>();
    for (let i = 0; i < 6000; i += 1) {
      const v = rng.ternary();
      expect([-1, 0, 1]).toContain(v);
      counts.set(v, (counts.get(v) ?? 0) + 1);
    }
    // Each value should land near 2000. A 25% window is loose enough never to
    // flake on a fixed seed and tight enough to catch a sampler stuck on two
    // of the three values.
    for (const v of [-1, 0, 1]) {
      expect(counts.get(v) ?? 0).toBeGreaterThan(1500);
      expect(counts.get(v) ?? 0).toBeLessThan(2500);
    }
  });

  it('cbd(21) has the standard deviation the parameters claim', () => {
    const rng = Rng.fromSeed('cbd');
    const N = 20000;
    let sum = 0;
    let sumSq = 0;
    let maxAbs = 0;
    for (let i = 0; i < N; i += 1) {
      const v = rng.cbd(21);
      sum += v;
      sumSq += v * v;
      maxAbs = Math.max(maxAbs, Math.abs(v));
    }
    const mean = sum / N;
    const variance = sumSq / N - mean * mean;
    // Var = eta / 2 = 10.5, so sigma = 3.2404...
    expect(Math.abs(mean)).toBeLessThan(0.15);
    expect(Math.sqrt(variance)).toBeGreaterThan(3.1);
    expect(Math.sqrt(variance)).toBeLessThan(3.4);
    // The hard support bound the noise arithmetic relies on.
    expect(maxAbs).toBeLessThanOrEqual(21);
  });
});
